### ISSUE TITLE
Prompt to become a member when logged in as a member

### ISSUE THREAD

**Issue by Mullefa** [guardian/membership-frontend#583]
Me again :D 

Title pretty much says it all. To add a little more detail, when I'm logged in as a member I get a bar across the bottom of my screen saying _Become a Guardian Member and support fearless investigative journalism_. If I click on this link, and then the resultant link _become a supporter_, I get taken to a page with a message saying: _unable to change from supporter to supporter_.

Based on the response to my last issue from @davidrapson, this may be one for [guardian/frontend](https://github.com/guardian/frontend). Apologies if I'm raising this in the wrong place.

**Comment by davidrapson** [comment]
Hi @Mullefa ,

Firstly, thank you for becoming a Supporter, even more so for trying to become a Supporter twice! This is definitely the place to raise this, I'm happy to pass on details to the appropriate team if needed anyway.

The banner you saw was part of an A/B test, which means it's not yet a permanent feature. We're aware that we show the message to existing members, which I agree is not ideal. We still have some work left to do before we can tell if you are a member from **theguardian.com**, which is why we showed it to you in this case, so for now I'm going to close this issue. It's definitely on our list though, so thanks for raising this.

When we make these banners more permanent we'll make sure we don't show them to existing members.

Hope that helps, and thanks again for the feedback,
David
