### ISSUE TITLE
YouTube (ytimg.com) giving us javascript console errors

### ISSUE THREAD

**Issue by rtyley** [guardian/membership-frontend#711]
![image](https://cloud.githubusercontent.com/assets/52038/9544814/8c43b458-4d7b-11e5-81ea-94c276478ffa.png)

This script:

https://s.ytimg.com/yts/jsbin/www-embed-player-new-vflhKdb6k/www-embed-player-new.js

Is trying load in all this stuff, and failing:

```
GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
...
```

GAH!

cc @davidrapson 

https://support.mozilla.org/en-US/questions/953550

**Comment by davidrapson** [comment]
Literally the only way to fix this is to install the Chrome-cast extension… 


Response from Google:
> Hey Everyone, we understand that this is annoying, and while this particular issue is marked WontFix, we are working on a solution that doesn't depend on being able to load content from the extension in this way.

As for the console error, this isn't a simple case of turning off a log statement, it's Chrome itself which shows that error on any failed document request.  Normally that's fairly useful to have, though we do understand it's annoying in this case due to the failed requests for extension resources.  There's really no way for the Cast JS code to suppress this console output, AFAIK.

See: https://code.google.com/p/google-cast-sdk/issues/detail?id=309

Worst thing is the error is logged on all browsers, not just Chrome.

:disappointed

**Comment by BarbiBimbo** [comment]
Still broken............... thanks google
